import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "gpm-website",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4 font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
